# Generated by Django 5.0 on 2024-01-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
